<a href="https://colab.research.google.com/github/KDK-00/deeplearning/blob/main/news_api_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **News 추천 알고리즘**

사용 전 Newsapi.org 홈페이지에 접속하여

개인 api key를 발급받아야 합니다.

In [25]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2024.6.2)

해당하는 부분에 발급받은 api key를 입력해주세요

In [26]:
import requests

# API 키 설정
API_KEY = '630646c0b54e41abb999fe00886bfe2c'
BASE_URL = 'https://newsapi.org/v2/'

In [27]:
def get_top_headlines(api_key, country='kr', category='general', page_size=10):
    url = f"{BASE_URL}top-headlines"  # BASE_URL에 이미 '/v2/'가 포함되어 있음
    params = {
        'apiKey': api_key,
        'country': country,
        'category': category,
        'pageSize': page_size
    }
    response = requests.get(url, params=params)

    # Check for HTTP errors
    response.raise_for_status()  # Raise an exception for bad status codes

    return response.json()

# 한국의 비즈니스 뉴스 헤드라인 가져오기
headlines = get_top_headlines(API_KEY)

# 결과 출력
for article in headlines['articles']:
    print(f"Title: {article['title']}")
    print(f"Description: {article['description']}")
    print(f"URL: {article['url']}")
    print("-" * 50)

Title: 메트로바니아풍 소울라이크 '더 라스트 페이스’ 실물 패키지 발매 - 인벤
Description: ㈜에이치투 인터렉티브(이하 H2 INTERACTIVE, 대표 허준하)는 쿠미 소울 게임즈(Kumi Souls Games)의 메트로바니아풍 소울라이크 게임 ‘더 라스트 페이스(The Last Faith)’의 실물 패키지인 ‘더 라스트 페이스:..
URL: https://www.inven.co.kr/webzine/news/?news=297219
--------------------------------------------------
Title: 손웅정 감독 '아동학대 논란'에 시민단체 토론회…"본질은 폭력" - 한국경제
Description: 손웅정 감독 '아동학대 논란'에 시민단체 토론회…"본질은 폭력", 사회
URL: https://www.hankyung.com/article/202407042434Y
--------------------------------------------------
Title: 삼성전자, 조직 개편 'HBM 개발팀' 신설…“HBM에 더 집중” - KBS뉴스
Description: 삼성전자가 HBM(고대역폭 메모리) 개발팀을 신설했습니다.<br /> <br />삼성전자 디바이스솔루션(DS) 부문은 오늘(4일) HBM 개발팀 신설을 골자로 하는 조직 개편을 실시했습니다.<br /> <br />메모리사업부 내에 있었던 HBM 전담 조직을 팀으로 신설한 것으로, 신임 팀장은 고성능 D램 제품 설계 전문가인 손영수 부사장이 맡기로 했습니다.<br /> <br />이 같은 HBM 개발팀 신설은 인공지능 시장 확대로 HBM 수요가 급증하면서, HB…
URL: https://news.kbs.co.kr/news/view.do?ncd=8003727
--------------------------------------------------
Title: 암 진단 후 이렇게 식사한 사람들, 더 오래 산다 - 동아일보
Description: 지중해식 식단이 암 환자의 수명 연장과도 관련이 있는 것으로 나타났다. 각종 암 진단을 받은 후 지중해식 식단을 잘 지킨 이들이 그렇지 않은 사람들에 비해 더 오래 살고, 심혈과…
URL: https://www.donga.com/news/It/article/all/20240704/125773212/1
--------------------------------------------------
Title: 스탠드업테라퓨티스, 반려동물 인지장애 치료 가능성 열었다 - 이데일리
Description: 뇌신경질환 유전자치료제 전문기업  스탠드업테라퓨티스가 반려동물 인지기능장애증후군(CDS) 치료의 새로운 가능성을 열었다. 잇단 반려동물 임상에서 긍정적인 데이터를 도출하며, 관련 시장의 혁신을 이끌 수 있을 것으로 기대된다. 반려견동물의 인지장애증후군 증상을 수치로 ...
URL: https://www.edaily.co.kr/News/Read?newsId=02765046638951240&amp;amp;mediaCodeNo=257
--------------------------------------------------
Title: 9명 사망 '시청역 역주행' 가해 운전자 체포영장 기각 - 한겨레
Description: 서울 도심에서 역주행 뒤 인도로 돌진해 9명을 숨지게 하고 7명을 다치게 한 차아무개(68)씨의 체포영장이 기각됐다. 서울 남대문경찰서는 서울중앙지법이 지난 3일 경찰이 신청한 피의자 체포영장을 기각했다고 이날 밝혔다. 경찰 설명을 들어보면, 법원은 ‘(차씨가) 출석에
URL: https://www.hani.co.kr/arti/society/society_general/1147696.html
--------------------------------------------------
Title: "더 줘 제발" 꽁꽁 싸매고 찾아와 '싹싹' 빌고 '벌벌' 떠는 환자들…돈다발 세는 병원 CCTV '충격 실태' (현장영상) / SBS - SBS 뉴스
Description: 경찰이 지난해 서울 강남구 일대에서 벌어진 이른바 '압구정 롤스로이스', '람보르기니 주차 시비' 사건에 연루된 병원 두 곳에 대한 추가 수사를 벌여 의사와 병원 관계자 등을 무더기로 검찰에 넘겼습니다.서울경찰청 마약범죄수사대는 의원 2곳의 의사 2명과 병원 관계자 14명, 투약자...
URL: https://www.youtube.com/watch?v=fCs5qr_LqkY
--------------------------------------------------
Title: ‘알투비트’, 여름맞이 업데이트 및 이벤트 전개 - 경향게임스
Description: 밸로프는 4일 자사에서 서비스 중인 리듬 온라인 게임 ‘알투비트(R2BEAT)’에서 시원한 여름을 위한 이벤트 및 신규 아이템을 선보인다고 밝혔다. 먼저, 이번 업데이트에서는 해변 테마 배경의 게임룸이 새롭게 변경됐으며, 매직볼에 여름 컨셉의 신규 코스튬이 추가 되었다. 23일까지 진행되는 7월 시원한 여름 이벤트는 총 3가지로, ‘시원한 여름 이벤트’, ‘키워드 이벤트’, ‘커뮤니티 이벤트’를 진행 중이다.‘시원한 여름 이벤트’는 출석 체크와 일일 미션을 완…
URL: https://www.khgames.co.kr/news/articleView.html?idxno=229678
--------------------------------------------------
Title: '팝업상륙작전' 박세리 “출연 결정 쉽지 않았지만…새로운 도전” - KBS뉴스
Description: "제가 알던 일반적인 방송이 아니었어요. 스케일이 너무 커서 부담을 많이 느꼈고, 출연을 결심하기까지 시간이 꽤 걸렸죠."<br /><br /> 해외 맛집의 메뉴를 팝업 행사를 통해 국내로 들어오는 예능 '팝업상륙작전'이 오는 6일 시청자들을 만난다.<br /><br /> KBS 2TV '팝업상륙작전'에 출연하는 골프선수 출신 박세리는 4일 온라인으로 열린 제작발표회에서 "제가 할 수 있는 범위 안에 일이 아니라고 생각했는데, 음식에 대한 관심을 바탕으로 새로…
URL: https://news.kbs.co.kr/news/view.do?ncd=8003705
--------------------------------------------------
Title: 檢총장, 野 검사탄핵에…“저급·비열한 외압에 절대 굴복 말라” - 동아일보
Description: 더불어민주당이 검사 4명에 대한 탄핵소추안을 발의한 가운데 이원석 검찰총장이 4일 “상대가 저급하고 비열하게 나오더라도 우리 검찰 구성원들은 위법하고 부당한 외압에 절대 굴복하지…
URL: https://www.donga.com/news/Politics/article/all/20240704/125772154/2
--------------------------------------------------

In [28]:
def get_top_headlines(api_key, country='kr', category='business', page_size=100, max_pages=5):
    url = f"{BASE_URL}top-headlines"
    all_articles = []
    for page in range(1, max_pages + 1):
        params = {
            'apiKey': api_key,
            'country': country,
            'category': category,
            'pageSize': page_size,
            'page': page
        }
        response = requests.get(url, params=params)
        response.raise_for_status()
        data = response.json()
        all_articles.extend(data['articles'])
        if len(data['articles']) < page_size:
            break  # 더 이상 기사가 없으면 중단
    return all_articles

# 한국의 비즈니스 뉴스 헤드라인 많이 가져오기
articles = get_top_headlines(API_KEY)

# 데이터 개수 확인
print(f"Total articles fetched: {len(articles)}")

Total articles fetched: 70

In [29]:
import re
import pandas as pd

def preprocess_articles(articles):
    cleaned_articles = []
    for article in articles:
        title = article['title'] if article['title'] else ''
        description = article['description'] if article['description'] else ''
        content = f"{title} {description}"
        content = re.sub(r'<[^>]+>', '', content)
        content = re.sub(r'[^a-zA-Z0-9가-힣\s]', '', content)
        cleaned_articles.append({
            'content': content.strip(),
            'source': article['source']['name'],
            'publishedAt': article['publishedAt']
        })
    return cleaned_articles

cleaned_articles = preprocess_articles(articles)

# DataFrame으로 정리
df = pd.DataFrame(cleaned_articles, columns=['content'])
print(df.head())

                                             content
0  삼성전자 조직 개편 HBM 개발팀 신설HBM에 더 집중  KBS뉴스 삼성전자가 HB...
1  골드만삭스 한은 8월 금리 인하할 것하반기 물가 20로 둔화  연합인포맥스 유력 투...
2  10명한테 물어놓고 10명 중 9명 합격에듀윌 과태료 500만원  한겨레 공무원 온...
3  서울 기후동행카드에 남양주시 참여8월 별내진접선 적용  연합뉴스 서울연합뉴스 김기훈...
4  빅테크 꼭지 신호인가젠슨 황 이어 베이조스도 주식 매각 나선다  매일경제 최근 신고...

In [30]:
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import linear_kernel

# def build_recommendation_model(cleaned_articles):
#     tfidf = TfidfVectorizer(stop_words='english')
#     tfidf_matrix = tfidf.fit_transform(cleaned_articles)
#     cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
#     return cosine_sim

# # 추천 모델 구축
# cosine_sim = build_recommendation_model(cleaned_articles)

# def recommend_articles(index, cosine_sim, df, top_n=5):
#     sim_scores = list(enumerate(cosine_sim[index]))
#     sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
#     sim_scores = sim_scores[1:top_n + 1]

#     article_indices = [i[0] for i in sim_scores]
#     return df.iloc[article_indices]

# # 첫 번째 기사와 유사한 기사 추천
# recommended_articles = recommend_articles(0, cosine_sim, df)
# print(recommended_articles)

In [31]:
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import json

# **json형식으로 API 가져오기**

In [32]:
import requests
url = ('https://newsapi.org/v2/top-headlines?'
       'country=kr&'
       'category=business&'
       'apiKey=630646c0b54e41abb999fe00886bfe2c')
response = requests.get(url)
print(response.json())

{'status': 'ok', 'totalResults': 70, 'articles': [{'source': {'id': None, 'name': 'Kbs.co.kr'}, 'author': '김지숙', 'title': "삼성전자, 조직 개편 'HBM 개발팀' 신설…“HBM에 더 집중” - KBS뉴스", 'description': '삼성전자가 HBM(고대역폭 메모리) 개발팀을 신설했습니다.<br /> <br />삼성전자 디바이스솔루션(DS) 부문은 오늘(4일) HBM 개발팀 신설을 골자로 하는 조직 개편을 실시했습니다.<br /> <br />메모리사업부 내에 있었던 HBM 전담 조직을 팀으로 신설한 것으로, 신임 팀장은 고성능 D램 제품 설계 전문가인 손영수 부사장이 맡기로 했습니다.<br /> <br />이 같은 HBM 개발팀 신설은 인공지능 시장 확대로 HBM 수요가 급증하면서, HB…', 'url': 'https://news.kbs.co.kr/news/view.do?ncd=8003727', 'urlToImage': 'http://news.kbs.co.kr/data/news/2024/07/04/20240704_qmlaaV.jpg', 'publishedAt': '2024-07-04T06:20:00Z', 'content': "HBM( ) .(DS) (4) HBM .\r\nHBM , D .\r\nHBM HBM , HBM .\r\nHBM3 HBM3E HBM4 .\r\n(AVP) .\r\nAVP AVP , .\r\n5 .\r\n.\r\n[ : / ]\r\n: 'KBS' , : 02-781-1234, 4444: kbs1234@kbs.co.kr, , KBS !"}, {'source': {'id': None, 'name': 'Einfomax.co.kr'}, 'author': '정윤교 기자', 'title': '골드만삭스 "한은 8월 금리 인하할 것…하반기 물가 2.0%로 둔화" - 연합인포맥스', 'description': '유력 투자은행 골드만삭스는 한국은행이 올해 8월 기준금리 인하에 나설 것으로 전망했다. 올해 하반기 국내 소비자물가 상승률이 한국은행의 목표치인 2.0%로 둔화할 것으로 내다보면서다.3일(현지시간) 다우존스에 따르면 골드만삭스 애널리스트들은 오는 11일 한국은행 금융통화위원회 회의에서 비둘기파(통화 완화 선호)적인 기조 전환이 예상된다며 이같이 밝혔다.이달 한은의 기조 전환은 내달 금리 인하의 포문을 열 수 있다고 관측했다.골드만삭스는 국내 인플레이션의 추가 …', 'url': 'https://news.einfomax.co.kr/news/articleView.html?idxno=4315858', 'urlToImage': 'https://cdn.news.einfomax.co.kr/news/thumbnail/202407/4315858_196524_581_v150.jpg', 'publishedAt': '2024-07-04T05:57:35Z', 'content': '[ . DB ]\r\n(=) = 8 . 2.0% .\r\n3() 11 ( ) .\r\n .\r\n , , 3.50% 25bp 2.50% .\r\n 3.1% 2.4% 2.0% .\r\n 2 6 2.4% . 7 11 .\r\n 2~3 3.1% 4 2.9%, 5 2.7% 2% .\r\nygjung@yna.co.kr\r\n()'}, {'source': {'id': None, 'name': 'Hani.co.kr'}, 'author': '안태호', 'title': '10명한테 물어놓고 “10명 중 9명 합격”…에듀윌 과태료 500만원 - 한겨레', 'description': '공무원 온라인 강의 서비스를 제공하는 에듀윌이 단 10명만 응답한 설문 결과를 근거로 높은 합격률을 광고했다가 적발돼 공정거래위원회로부터 제재를 받았다. 공정위는 4일 에듀윌의 전자상거래법 위반행위에 대해 시정명령과 함께 과태료 500만원을 부과했다고 밝혔다. 에듀윌은', 'url': 'https://www.hani.co.kr/arti/economy/economy_general/1147686.html', 'urlToImage': 'https://flexible.img.hani.co.kr/flexible/normal/691/405/imgdb/original/2024/0704/20240704501684.jpg', 'publishedAt': '2024-07-04T05:22:00Z', 'content': None}, {'source': {'id': None, 'name': 'Yna.co.kr'}, 'author': '김기훈', 'title': '서울 기후동행카드에 남양주시 참여…8월 별내·진접선 적용 - 연합뉴스', 'description': "(서울=연합뉴스) 김기훈 기자 = 8월 지하철 8호선의 연장 별내선 개통에 맞춰 별내선 6개 역사에서도 서울시 '기후동행카드'를 사용할 수 있게...", 'url': 'https://www.yna.co.kr/view/AKR20240704018700004', 'urlToImage': 'https://img4.yna.co.kr/photo/yna/YH/2024/07/04/PYH2024070415410001300_P4.jpg', 'publishedAt': '2024-07-04T05:10:00Z', 'content': "- (=) 4 - . 2024.7.4 [ . DB ] photo@yna.co.kr\r\n(=) = 8 8 6 '' . \r\n 4 3 .\r\n 74 .\r\n4 6 '- ' .\r\n .\r\n .\r\n 6 (·····) 8 24 .\r\n 4 3 (··) .\r\n , .\r\n 3 .\r\n , .\r\n 3 (202, 1155, 2212) .\r\n 13 , () .\r\n 1 27 70 100… [+156 chars]"}, {'source': {'id': None, 'name': 'Mk.co.kr'}, 'author': '이덕주', 'title': '“빅테크 꼭지 신호인가?”...젠슨 황 이어 베이조스도 주식 매각 나선다 - 매일경제', 'description': '최근 신고가를 경신하고 있는 주요 빅테크 기업들의 창업자들이 주식을 매각하면서 주가가 고점이 아닌가라는 우려가 커지고 있다. 3일(현지시간) 블룸버그는 젠슨 황 엔비디아 CEO가 지난 달 엔비디아 주식 130만주를 팔았다고 미 증권거래위원회(SEC)에 제출된 자료를 기반으로 보도했다. 130만주는 1억6900만달러(약 2300억원)에 달한다. 젠슨 황 CE', 'url': 'https://www.mk.co.kr/news/business/11058688', 'urlToImage': 'https://wimg-orig.mk.co.kr/news/cms/202407/04/news-p.v1.20240704.db74756f7b5a401097f633d5628d7ab0_P1.png', 'publishedAt': '2024-07-04T04:53:51Z', 'content': '.\r\n3() CEO 130 (SEC) . 130 16900( 2300) .\r\n CEO 3 SEC 3 60(10 1 ) . , .\r\n CEO , 7 .\r\n CEO . 2 SEC 2500 . 50 .\r\n 2 85( 117600) 9 .\r\n 8.8%(91200) .\r\n 2021 CEO . .\r\n[= ]'}, {'source': {'id': None, 'name': 'Insidevina.com'}, 'author': '떤 풍(Tan phung) 기자', 'title': '베트남 총리, 삼성전자 평택캠퍼스 방문…방한일정 마무리 - 인사이드비나', 'description': '[인사이드비나=하노이, 떤 풍(Tan phung) 기자] 팜 민 찐(Pham Minh Chinh) 베트남 총리가 방한일정 마지막날인 지난 3일 평택 삼성전자 반도체공장을 방문해 생산시설을 둘러보고, 자국 첨단산업에 대한 투자 확대를 요청했다.찐 총리 내외는 한덕수 국무총리의 초청으로 지난달 30일부터 3일까지 나흘간 일정으로 방한했다.이날 찐 총리의 평택캠퍼스 방문에는 삼성전자 반도체사업 책임자인 전영현 DS 부문장(부회장), 박학규 SET부문 경영지원실장(C…', 'url': 'http://www.insidevina.com/news/articleView.html?idxno=27998', 'urlToImage': 'http://www.insidevina.com/news/thumbnail/202407/27998_31568_2145_v150.jpg', 'publishedAt': '2024-07-04T04:24:07Z', 'content': '[=, (Tan phung) ]\xa0 (Pham Minh Chinh) 3 , .\r\n 30 3 .\r\n DS (), SET (CFO·) .\r\n “ , ” “ ” .\r\n “ 20 ” “ , , ” .\r\n “ AI() , , ” .\r\n - .\r\n , , HS , , .'}, {'source': {'id': None, 'name': 'Mediatoday.co.kr'}, 'author': '윤수현 기자', 'title': '넷플릭스, 베이직 요금제 완전 폐지 수순 - 미디어오늘', 'description': '넷플릭스가 캐나다·영국에서 베이직 요금제를 완전 폐지하기로 했다. 베이직 요금제 유지를 허용하고 있는 미국 등 다른 나라에서도 완전 폐지 조치가 시행될 것이라는 전망이 나온다.미국 IT 전문매체 더버지의 지난 2일 보도에 따르면 넷플릭스는 최근 베이직 요금제(한국기준 월 9500원)를 유지하고 있는 캐나다·영국 이용자에게 “7월13일까지만 넷플릭스를 이용할 수 있다. 계속 시청하려면 새로운 요금제를 선택하라”고 했다. 베이직 요금제 가입자가 넷플릭스를 계속 이…', 'url': 'https://www.mediatoday.co.kr/news/articleView.html?idxno=319229', 'urlToImage': 'https://cdn.mediatoday.co.kr/news/thumbnail/202407/319229_449704_276_v150.jpg', 'publishedAt': '2024-07-04T04:11:30Z', 'content': '· . .\r\n IT 2 ( 9500) · “713 . ” . ( 5500) ( 13500)·(17000) .\r\n 6 ··· . , 13 · .\r\n . “ OTT ” “ 5 4000 ” .\r\nIT . 2 “ · , ” “ 2 · ” .\r\n 12 , . “ ” .\r\n12 ‘ ’ . () . 4 “ ” .\r\n 5500 , 13500 , 17000 . (1080… [+41 chars]'}, {'source': {'id': None, 'name': 'Kita.net'}, 'author': None, 'title': '반도체장비 세계 1위 ASML, 화성에 1조원대 연구개발 시설 건립 - 한국무역협회', 'description': '한국무역협회 무역 통상정보, 회원/업무지원, 무역통계, 협회안내 등 서비스 안내.', 'url': 'https://www.kita.net/board/totalTradeNews/totalTradeNewsDetail.do;JSESSIONID_KITA=0943EDA3052450E366060AC756AF69E1.Hyper?no=84803&amp;siteId=1', 'urlToImage': 'https://kita.net/imgs/common/kita_logo_mid.png', 'publishedAt': '2024-07-04T04:06:37Z', 'content': '1 ASML, 1 \r\n \'ASML- \' \r\n ASML ( ) ()\xa0\r\n ASML (High NA EUV) . ASML 4 .\r\nASML (EUV) ( ) 1 , 2 .\r\n "1 \'ASML- \' " " ASML " .\r\n " \'ASML \' " " ASML " . .\r\n . ASML 28 \'ASML- \' . K- 8 ASML CEO .\r\n[ ]'}, {'source': {'id': None, 'name': 'Hankyung.com'}, 'author': '차은지', 'title': "편하게 살 빼려다 '실명' 될라…충격 연구결과 나왔다 - 한국경제", 'description': '편하게 살 빼려다 \'실명\' 될라…충격 연구결과 나왔다, "위고비 복용시 \'눈 뇌졸중\' 발병 가능성↑" 당뇨·비만환자 처방시 \'눈 뇌졸중\' 발병 가능성 4∼7배', 'url': 'https://www.hankyung.com/article/2024070419307', 'urlToImage': 'https://img.hankyung.com/photo/202407/99.34985003.1.jpg', 'publishedAt': '2024-07-04T03:53:55Z', 'content': '. /=\r\n.3() CNN · \' \' \'\'(NAION) .\r\nNAION \' \' . .\r\n10 10 3 . .\r\n· , GLP-1( -1) .\r\n6 NAION 4 · 7 .\r\n\' -\'(JAMA Ophthalmology) .\r\n" NAION " .\r\nNAION CNN .\r\nNAION CNN . .\r\nchachacha@hankyung.com'}, {'source': {'id': None, 'name': 'Khan.co.kr'}, 'author': '경향신문', 'title': '가상자산사업자 불시 영업종료? 앞으론 한달전에 이용자 보호안 제출해야 - 경향신문', 'description': None, 'url': 'https://m.khan.co.kr/economy/finance/article/202407041220001', 'urlToImage': None, 'publishedAt': '2024-07-04T03:20:00Z', 'content': None}, {'source': {'id': None, 'name': 'Einfomax.co.kr'}, 'author': '김정현 기자', 'title': '1분기 가계 여유자금 48조↑…정부 순조달 역대급 - 연합인포맥스', 'description': '지난 1분기 가계의 여유 자금이 크게 늘어났다. 부동산 분양 물량이 많지 않아 가계가 조달보다 운용을 늘린 것으로 보인다.정부의 경우 적극재정 기조 등에 따라 통계 편제 후 가장 큰 순자금조달을 나타냈다. 기업은 당기순이익 증가 등을 반영해 순자금조달 규모가 다소 축소됐다.한국은행이 4일 발표한 2024년 1분기 자금순환(잠정)에 따르면 가계(개인사업자 포함) 및 비영리단체의 지난 1분기 순자금운용(자금운용 - 자금조달) 규모는 77조6천억 원으로 나타났다. …', 'url': 'https://news.einfomax.co.kr/news/articleView.html?idxno=4315838', 'urlToImage': 'https://cdn.news.einfomax.co.kr/news/thumbnail/202407/4315838_196507_41_v150.jpg', 'publishedAt': '2024-07-04T03:03:26Z', 'content': '1 \r\n, \r\n 1 \r\n(=) = 1 . .\r\n . .\r\n 4 2024 1 () ( ) 1 ( - ) 776 . (298 ) 478 . 1 (856 ) 6 .\r\n .\r\n 1 4.5% 2% .\r\n1 64 (86) . 4 65 1 61 .\r\n " 1 " " " .\r\n(39 →79 ) 4 184 586 . (73 →124 ), (-131 →29 ) .\r\n(92… [+174 chars]'}, {'source': {'id': None, 'name': 'YouTube'}, 'author': None, 'title': '횡령 여파에 성과급 환수.. 직원들 날벼락 (2024.07.03/뉴스데스크/MBC경남) - MBCNEWS', 'description': None, 'url': 'https://www.youtube.com/watch?v=oWjQ407PihA', 'urlToImage': None, 'publishedAt': '2024-07-04T03:00:36Z', 'content': 'Your browser isnt supported anymore. Update it to get the best YouTube experience and our latest features. Learn more\r\nRemind me later'}, {'source': {'id': 'google-news', 'name': 'Google News'}, 'author': '머니투데이', 'title': '국민 88%는 금융투자자..."금투세 도입 시 투자 축소" - 머니투데이', 'description': None, 'url': 'https://news.google.com/rss/articles/CBMiN2h0dHBzOi8vbmV3cy5tdC5jby5rci9tdHZpZXcucGhwP25vPTIwMjQwNzA0MTA1NTE1MTUzMTPSAT1odHRwczovL20ubXQuY28ua3IvcmVuZXcvdmlld19hbXAuaHRtbD9ubz0yMDI0MDcwNDEwNTUxNTE1MzEz?oc=5', 'urlToImage': None, 'publishedAt': '2024-07-04T03:00:04Z', 'content': None}, {'source': {'id': None, 'name': 'Munhwa.com'}, 'author': '문화일보', 'title': '中 저가 공세에… 철강수출 2년째↓ - 문화일보', 'description': None, 'url': 'https://www.munhwa.com/news/view.html?no=2024070401071707207001', 'urlToImage': None, 'publishedAt': '2024-07-04T02:59:00Z', 'content': None}, {'source': {'id': None, 'name': 'YouTube'}, 'author': None, 'title': "[자막뉴스] 방콕 가는 대한항공 승무원 가방에 소총탄이.. '발칵' (2024.07.04/MBC뉴스) - MBCNEWS", 'description': None, 'url': 'https://www.youtube.com/watch?v=-7Xnl_2gtJQ', 'urlToImage': None, 'publishedAt': '2024-07-04T02:49:03Z', 'content': 'Your browser isnt supported anymore. Update it to get the best YouTube experience and our latest features. Learn more\r\nRemind me later'}, {'source': {'id': None, 'name': 'Electimes.com'}, 'author': '김부미 기자', 'title': '상반기 모빌리티용 수소 3790t 소비…전년比 46% 증가 - 전기신문', 'description': "올 상반기 모빌리티용 수소 소비량이 지난해보다 46% 증가한 것으로 나타났다.4일 산업통상자원부에 따르면 상반기 모빌리티용 수소 소비량은 3790t으로 전년 동기보다 46% 증가했다.산업부는 하반기 모빌리티용 수소 수요량을 8400t에 달할 것으로 보고 있다. 액화수소플랜트 등에서 최대 1만3000t이 생산돼 공급에는 차질이 없을 것으로 내다봤다.이날 산업부는 서울 코리아나호텔에서 '2024년 제2차 모빌리티용 수소 수급 협의체 회의'를 열고 상반기 추진 실적…", 'url': 'https://www.electimes.com/news/articleView.html?idxno=339770', 'urlToImage': 'https://cdn.electimes.com/news/thumbnail/202407/339770_542657_246_v150.jpg', 'publishedAt': '2024-07-04T02:24:16Z', 'content': '46% .\r\n4 3790t 46% .\r\n 8400t . 13000t .\r\n \'2024 2 \' · .\r\n , , .\r\n , .\r\n " " " , " .\r\nboomi@electimes.com\r\n © \r\n<ul><li> : </li><li> : ()</li><li> 15 53 A 3</li><li> : 02-6949-4636</li><li> : 02-6949-… [+195 chars]'}, {'source': {'id': None, 'name': 'Businesspost.co.kr'}, 'author': None, 'title': "LG엔솔 배터리 '게임 체인저' 건식 코팅 2028년 상용화, 김제영 “건식코팅 LG가 1위” - 비즈니스포스트", 'description': None, 'url': 'https://www.businesspost.co.kr/BP?command=article_view&amp;num=357804', 'urlToImage': None, 'publishedAt': '2024-07-04T01:55:30Z', 'content': None}, {'source': {'id': None, 'name': 'Chosun.com'}, 'author': '조선비즈', 'title': 'AI붐 타고 수출 효자된 전력기자재, 스마트폰까지 제쳤다 - 조선비즈 - 조선비즈', 'description': 'AI붐 타고 수출 효자된 전력기자재, 스마트폰까지 제쳤다 산업부, HD현대일렉트릭서 전력기자재 업계 간담회   한전·코트라·무보 K-그리드 수출지원 MOU 체결', 'url': 'https://biz.chosun.com/policy/policy_sub/2024/07/04/4APX6OBYQFCWZJM6O2WAK232BU/', 'urlToImage': 'https://biz.chosun.com/resizer/DKYk9ouKmirmCBZ2_NVdrAW4AkI=/1200x630/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosunbiz/MOLRRIWL2RB7FPDQENL362BLXQ.jpg', 'publishedAt': '2024-07-04T01:44:00Z', 'content': None}, {'source': {'id': None, 'name': 'Chosun.com'}, 'author': '조선일보', 'title': 'AI반도체 시급한 중국, 유학생까지 동원하며 엔비디아 칩 밀수 - 조선일보', 'description': 'AI반도체 시급한 중국, 유학생까지 동원하며 엔비디아 칩 밀수', 'url': 'https://www.chosun.com/economy/tech_it/2024/07/04/GKOMTMFN6VC3DEFGJED5ASM4BE/', 'urlToImage': 'https://images.chosun.com/resizer/jD1rjZfu7LHLAZzC2CAkGZ7Jtwc=/1200x630/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosun/FJSVCXQLHIKETLRJRPOQ6PXFME.jpg', 'publishedAt': '2024-07-04T01:33:00Z', 'content': None}, {'source': {'id': None, 'name': 'Newdaily.co.kr'}, 'author': None, 'title': "[단독] '가계대출 비상등' 국민은행, 씨티은행 대환대출 이자지원 중단 - 뉴데일리경제", 'description': 'KB국민은행이 한국씨티은행과의 제휴를 통해 대환대출 고객들에게 제공해 온 이자지원을 중단한 것으로 확인됐다.금융당국이 다시금 가계대출 증가세에 대한 감시의 불을 켜고 있어 부동산담보대출 금리 인상에 이어 대환대출까지 혜택을 대폭 줄이며 속도조절에 나선 것이다.4일 금융권에 따르면 국민은행은 씨티은행 고객들을 대상으로 하는 ‘KB 제휴 대환 신용대출’ 이자지원 혜택을 이달부터 중단했다.앞서 국민은행은 소매금융 사업에서 철수한...', 'url': 'https://biz.newdaily.co.kr/site/data/html/2024/07/04/2024070400074.html', 'urlToImage': 'https://image.newdaily.co.kr/site/data/img/2024/07/04/2024070400074_0.jpg', 'publishedAt': '2024-07-04T01:30:17Z', 'content': None}]}

In [33]:
json.loads(response.text)

{'status': 'ok',
 'totalResults': 70,
 'articles': [{'source': {'id': None, 'name': 'Kbs.co.kr'},
   'author': '김지숙',
   'title': "삼성전자, 조직 개편 'HBM 개발팀' 신설…“HBM에 더 집중” - KBS뉴스",
   'description': '삼성전자가 HBM(고대역폭 메모리) 개발팀을 신설했습니다.<br /> <br />삼성전자 디바이스솔루션(DS) 부문은 오늘(4일) HBM 개발팀 신설을 골자로 하는 조직 개편을 실시했습니다.<br /> <br />메모리사업부 내에 있었던 HBM 전담 조직을 팀으로 신설한 것으로, 신임 팀장은 고성능 D램 제품 설계 전문가인 손영수 부사장이 맡기로 했습니다.<br /> <br />이 같은 HBM 개발팀 신설은 인공지능 시장 확대로 HBM 수요가 급증하면서, HB…',
   'url': 'https://news.kbs.co.kr/news/view.do?ncd=8003727',
   'urlToImage': 'http://news.kbs.co.kr/data/news/2024/07/04/20240704_qmlaaV.jpg',
   'publishedAt': '2024-07-04T06:20:00Z',
   'content': "HBM( ) .(DS) (4) HBM .\r\nHBM , D .\r\nHBM HBM , HBM .\r\nHBM3 HBM3E HBM4 .\r\n(AVP) .\r\nAVP AVP , .\r\n5 .\r\n.\r\n[ : / ]\r\n: 'KBS' , : 02-781-1234, 4444: kbs1234@kbs.co.kr, , KBS !"},
  {'source': {'id': None, 'name': 'Einfomax.co.kr'},
   'author': '정윤교 기자',
   'title': '골드만삭스 "한은 8월 금리 인하할 것…하반기 물가 2.0%로 둔화" - 연합인포맥스',
   'description': '유력 투자은행 골드만삭스는 한국은행이 올해 8월 기준금리 인하에 나설 것으로 전망했다. 올해 하반기 국내 소비자물가 상승률이 한국은행의 목표치인 2.0%로 둔화할 것으로 내다보면서다.3일(현지시간) 다우존스에 따르면 골드만삭스 애널리스트들은 오는 11일 한국은행 금융통화위원회 회의에서 비둘기파(통화 완화 선호)적인 기조 전환이 예상된다며 이같이 밝혔다.이달 한은의 기조 전환은 내달 금리 인하의 포문을 열 수 있다고 관측했다.골드만삭스는 국내 인플레이션의 추가 …',
   'url': 'https://news.einfomax.co.kr/news/articleView.html?idxno=4315858',
   'urlToImage': 'https://cdn.news.einfomax.co.kr/news/thumbnail/202407/4315858_196524_581_v150.jpg',
   'publishedAt': '2024-07-04T05:57:35Z',
   'content': '[ . DB ]\r\n(=) = 8 . 2.0% .\r\n3() 11 ( ) .\r\n .\r\n , , 3.50% 25bp 2.50% .\r\n 3.1% 2.4% 2.0% .\r\n 2 6 2.4% . 7 11 .\r\n 2~3 3.1% 4 2.9%, 5 2.7% 2% .\r\nygjung@yna.co.kr\r\n()'},
  {'source': {'id': None, 'name': 'Hani.co.kr'},
   'author': '안태호',
   'title': '10명한테 물어놓고 “10명 중 9명 합격”…에듀윌 과태료 500만원 - 한겨레',
   'description': '공무원 온라인 강의 서비스를 제공하는 에듀윌이 단 10명만 응답한 설문 결과를 근거로 높은 합격률을 광고했다가 적발돼 공정거래위원회로부터 제재를 받았다. 공정위는 4일 에듀윌의 전자상거래법 위반행위에 대해 시정명령과 함께 과태료 500만원을 부과했다고 밝혔다. 에듀윌은',
   'url': 'https://www.hani.co.kr/arti/economy/economy_general/1147686.html',
   'urlToImage': 'https://flexible.img.hani.co.kr/flexible/normal/691/405/imgdb/original/2024/0704/20240704501684.jpg',
   'publishedAt': '2024-07-04T05:22:00Z',
   'content': None},
  {'source': {'id': None, 'name': 'Yna.co.kr'},
   'author': '김기훈',
   'title': '서울 기후동행카드에 남양주시 참여…8월 별내·진접선 적용 - 연합뉴스',
   'description': "(서울=연합뉴스) 김기훈 기자 = 8월 지하철 8호선의 연장 별내선 개통에 맞춰 별내선 6개 역사에서도 서울시 '기후동행카드'를 사용할 수 있게...",
   'url': 'https://www.yna.co.kr/view/AKR20240704018700004',
   'urlToImage': 'https://img4.yna.co.kr/photo/yna/YH/2024/07/04/PYH2024070415410001300_P4.jpg',
   'publishedAt': '2024-07-04T05:10:00Z',
   'content': "- (=) 4 - . 2024.7.4 [ . DB ] photo@yna.co.kr\r\n(=) = 8 8 6 '' . \r\n 4 3 .\r\n 74 .\r\n4 6 '- ' .\r\n .\r\n .\r\n 6 (·····) 8 24 .\r\n 4 3 (··) .\r\n , .\r\n 3 .\r\n , .\r\n 3 (202, 1155, 2212) .\r\n 13 , () .\r\n 1 27 70 100… [+156 chars]"},
  {'source': {'id': None, 'name': 'Mk.co.kr'},
   'author': '이덕주',
   'title': '“빅테크 꼭지 신호인가?”...젠슨 황 이어 베이조스도 주식 매각 나선다 - 매일경제',
   'description': '최근 신고가를 경신하고 있는 주요 빅테크 기업들의 창업자들이 주식을 매각하면서 주가가 고점이 아닌가라는 우려가 커지고 있다. 3일(현지시간) 블룸버그는 젠슨 황 엔비디아 CEO가 지난 달 엔비디아 주식 130만주를 팔았다고 미 증권거래위원회(SEC)에 제출된 자료를 기반으로 보도했다. 130만주는 1억6900만달러(약 2300억원)에 달한다. 젠슨 황 CE',
   'url': 'https://www.mk.co.kr/news/business/11058688',
   'urlToImage': 'https://wimg-orig.mk.co.kr/news/cms/202407/04/news-p.v1.20240704.db74756f7b5a401097f633d5628d7ab0_P1.png',
   'publishedAt': '2024-07-04T04:53:51Z',
   'content': '.\r\n3() CEO 130 (SEC) . 130 16900( 2300) .\r\n CEO 3 SEC 3 60(10 1 ) . , .\r\n CEO , 7 .\r\n CEO . 2 SEC 2500 . 50 .\r\n 2 85( 117600) 9 .\r\n 8.8%(91200) .\r\n 2021 CEO . .\r\n[= ]'},
  {'source': {'id': None, 'name': 'Insidevina.com'},
   'author': '떤 풍(Tan phung) 기자',
   'title': '베트남 총리, 삼성전자 평택캠퍼스 방문…방한일정 마무리 - 인사이드비나',
   'description': '[인사이드비나=하노이, 떤 풍(Tan phung) 기자] 팜 민 찐(Pham Minh Chinh) 베트남 총리가 방한일정 마지막날인 지난 3일 평택 삼성전자 반도체공장을 방문해 생산시설을 둘러보고, 자국 첨단산업에 대한 투자 확대를 요청했다.찐 총리 내외는 한덕수 국무총리의 초청으로 지난달 30일부터 3일까지 나흘간 일정으로 방한했다.이날 찐 총리의 평택캠퍼스 방문에는 삼성전자 반도체사업 책임자인 전영현 DS 부문장(부회장), 박학규 SET부문 경영지원실장(C…',
   'url': 'http://www.insidevina.com/news/articleView.html?idxno=27998',
   'urlToImage': 'http://www.insidevina.com/news/thumbnail/202407/27998_31568_2145_v150.jpg',
   'publishedAt': '2024-07-04T04:24:07Z',
   'content': '[=, (Tan phung) ]\xa0 (Pham Minh Chinh) 3 , .\r\n 30 3 .\r\n DS (), SET (CFO·) .\r\n “ , ” “ ” .\r\n “ 20 ” “ , , ” .\r\n “ AI() , , ” .\r\n - .\r\n , , HS , , .'},
  {'source': {'id': None, 'name': 'Mediatoday.co.kr'},
   'author': '윤수현 기자',
   'title': '넷플릭스, 베이직 요금제 완전 폐지 수순 - 미디어오늘',
   'description': '넷플릭스가 캐나다·영국에서 베이직 요금제를 완전 폐지하기로 했다. 베이직 요금제 유지를 허용하고 있는 미국 등 다른 나라에서도 완전 폐지 조치가 시행될 것이라는 전망이 나온다.미국 IT 전문매체 더버지의 지난 2일 보도에 따르면 넷플릭스는 최근 베이직 요금제(한국기준 월 9500원)를 유지하고 있는 캐나다·영국 이용자에게 “7월13일까지만 넷플릭스를 이용할 수 있다. 계속 시청하려면 새로운 요금제를 선택하라”고 했다. 베이직 요금제 가입자가 넷플릭스를 계속 이…',
   'url': 'https://www.mediatoday.co.kr/news/articleView.html?idxno=319229',
   'urlToImage': 'https://cdn.mediatoday.co.kr/news/thumbnail/202407/319229_449704_276_v150.jpg',
   'publishedAt': '2024-07-04T04:11:30Z',
   'content': '· . .\r\n IT 2 ( 9500) · “713 . ” . ( 5500) ( 13500)·(17000) .\r\n 6 ··· . , 13 · .\r\n . “ OTT ” “ 5 4000 ” .\r\nIT . 2 “ · , ” “ 2 · ” .\r\n 12 , . “ ” .\r\n12 ‘ ’ . () . 4 “ ” .\r\n 5500 , 13500 , 17000 . (1080… [+41 chars]'},
  {'source': {'id': None, 'name': 'Kita.net'},
   'author': None,
   'title': '반도체장비 세계 1위 ASML, 화성에 1조원대 연구개발 시설 건립 - 한국무역협회',
   'description': '한국무역협회 무역 통상정보, 회원/업무지원, 무역통계, 협회안내 등 서비스 안내.',
   'url': 'https://www.kita.net/board/totalTradeNews/totalTradeNewsDetail.do;JSESSIONID_KITA=0943EDA3052450E366060AC756AF69E1.Hyper?no=84803&amp;siteId=1',
   'urlToImage': 'https://kita.net/imgs/common/kita_logo_mid.png',
   'publishedAt': '2024-07-04T04:06:37Z',
   'content': '1 ASML, 1 \r\n \'ASML- \' \r\n ASML ( ) ()\xa0\r\n ASML (High NA EUV) . ASML 4 .\r\nASML (EUV) ( ) 1 , 2 .\r\n "1 \'ASML- \' " " ASML " .\r\n " \'ASML \' " " ASML " . .\r\n . ASML 28 \'ASML- \' . K- 8 ASML CEO .\r\n[ ]'},
  {'source': {'id': None, 'name': 'Hankyung.com'},
   'author': '차은지',
   'title': "편하게 살 빼려다 '실명' 될라…충격 연구결과 나왔다 - 한국경제",
   'description': '편하게 살 빼려다 \'실명\' 될라…충격 연구결과 나왔다, "위고비 복용시 \'눈 뇌졸중\' 발병 가능성↑" 당뇨·비만환자 처방시 \'눈 뇌졸중\' 발병 가능성 4∼7배',
   'url': 'https://www.hankyung.com/article/2024070419307',
   'urlToImage': 'https://img.hankyung.com/photo/202407/99.34985003.1.jpg',
   'publishedAt': '2024-07-04T03:53:55Z',
   'content': '. /=\r\n.3() CNN · \' \' \'\'(NAION) .\r\nNAION \' \' . .\r\n10 10 3 . .\r\n· , GLP-1( -1) .\r\n6 NAION 4 · 7 .\r\n\' -\'(JAMA Ophthalmology) .\r\n" NAION " .\r\nNAION CNN .\r\nNAION CNN . .\r\nchachacha@hankyung.com'},
  {'source': {'id': None, 'name': 'Khan.co.kr'},
   'author': '경향신문',
   'title': '가상자산사업자 불시 영업종료? 앞으론 한달전에 이용자 보호안 제출해야 - 경향신문',
   'description': None,
   'url': 'https://m.khan.co.kr/economy/finance/article/202407041220001',
   'urlToImage': None,
   'publishedAt': '2024-07-04T03:20:00Z',
   'content': None},
  {'source': {'id': None, 'name': 'Einfomax.co.kr'},
   'author': '김정현 기자',
   'title': '1분기 가계 여유자금 48조↑…정부 순조달 역대급 - 연합인포맥스',
   'description': '지난 1분기 가계의 여유 자금이 크게 늘어났다. 부동산 분양 물량이 많지 않아 가계가 조달보다 운용을 늘린 것으로 보인다.정부의 경우 적극재정 기조 등에 따라 통계 편제 후 가장 큰 순자금조달을 나타냈다. 기업은 당기순이익 증가 등을 반영해 순자금조달 규모가 다소 축소됐다.한국은행이 4일 발표한 2024년 1분기 자금순환(잠정)에 따르면 가계(개인사업자 포함) 및 비영리단체의 지난 1분기 순자금운용(자금운용 - 자금조달) 규모는 77조6천억 원으로 나타났다. …',
   'url': 'https://news.einfomax.co.kr/news/articleView.html?idxno=4315838',
   'urlToImage': 'https://cdn.news.einfomax.co.kr/news/thumbnail/202407/4315838_196507_41_v150.jpg',
   'publishedAt': '2024-07-04T03:03:26Z',
   'content': '1 \r\n, \r\n 1 \r\n(=) = 1 . .\r\n . .\r\n 4 2024 1 () ( ) 1 ( - ) 776 . (298 ) 478 . 1 (856 ) 6 .\r\n .\r\n 1 4.5% 2% .\r\n1 64 (86) . 4 65 1 61 .\r\n " 1 " " " .\r\n(39 →79 ) 4 184 586 . (73 →124 ), (-131 →29 ) .\r\n(92… [+174 chars]'},
  {'source': {'id': None, 'name': 'YouTube'},
   'author': None,
   'title': '횡령 여파에 성과급 환수.. 직원들 날벼락 (2024.07.03/뉴스데스크/MBC경남) - MBCNEWS',
   'description': None,
   'url': 'https://www.youtube.com/watch?v=oWjQ407PihA',
   'urlToImage': None,
   'publishedAt': '2024-07-04T03:00:36Z',
   'content': 'Your browser isnt supported anymore. Update it to get the best YouTube experience and our latest features. Learn more\r\nRemind me later'},
  {'source': {'id': 'google-news', 'name': 'Google News'},
   'author': '머니투데이',
   'title': '국민 88%는 금융투자자..."금투세 도입 시 투자 축소" - 머니투데이',
   'description': None,
   'url': 'https://news.google.com/rss/articles/CBMiN2h0dHBzOi8vbmV3cy5tdC5jby5rci9tdHZpZXcucGhwP25vPTIwMjQwNzA0MTA1NTE1MTUzMTPSAT1odHRwczovL20ubXQuY28ua3IvcmVuZXcvdmlld19hbXAuaHRtbD9ubz0yMDI0MDcwNDEwNTUxNTE1MzEz?oc=5',
   'urlToImage': None,
   'publishedAt': '2024-07-04T03:00:04Z',
   'content': None},
  {'source': {'id': None, 'name': 'Munhwa.com'},
   'author': '문화일보',
   'title': '中 저가 공세에… 철강수출 2년째↓ - 문화일보',
   'description': None,
   'url': 'https://www.munhwa.com/news/view.html?no=2024070401071707207001',
   'urlToImage': None,
   'publishedAt': '2024-07-04T02:59:00Z',
   'content': None},
  {'source': {'id': None, 'name': 'YouTube'},
   'author': None,
   'title': "[자막뉴스] 방콕 가는 대한항공 승무원 가방에 소총탄이.. '발칵' (2024.07.04/MBC뉴스) - MBCNEWS",
   'description': None,
   'url': 'https://www.youtube.com/watch?v=-7Xnl_2gtJQ',
   'urlToImage': None,
   'publishedAt': '2024-07-04T02:49:03Z',
   'content': 'Your browser isnt supported anymore. Update it to get the best YouTube experience and our latest features. Learn more\r\nRemind me later'},
  {'source': {'id': None, 'name': 'Electimes.com'},
   'author': '김부미 기자',
   'title': '상반기 모빌리티용 수소 3790t 소비…전년比 46% 증가 - 전기신문',
   'description': "올 상반기 모빌리티용 수소 소비량이 지난해보다 46% 증가한 것으로 나타났다.4일 산업통상자원부에 따르면 상반기 모빌리티용 수소 소비량은 3790t으로 전년 동기보다 46% 증가했다.산업부는 하반기 모빌리티용 수소 수요량을 8400t에 달할 것으로 보고 있다. 액화수소플랜트 등에서 최대 1만3000t이 생산돼 공급에는 차질이 없을 것으로 내다봤다.이날 산업부는 서울 코리아나호텔에서 '2024년 제2차 모빌리티용 수소 수급 협의체 회의'를 열고 상반기 추진 실적…",
   'url': 'https://www.electimes.com/news/articleView.html?idxno=339770',
   'urlToImage': 'https://cdn.electimes.com/news/thumbnail/202407/339770_542657_246_v150.jpg',
   'publishedAt': '2024-07-04T02:24:16Z',
   'content': '46% .\r\n4 3790t 46% .\r\n 8400t . 13000t .\r\n \'2024 2 \' · .\r\n , , .\r\n , .\r\n " " " , " .\r\nboomi@electimes.com\r\n © \r\n<ul><li> : </li><li> : ()</li><li> 15 53 A 3</li><li> : 02-6949-4636</li><li> : 02-6949-… [+195 chars]'},
  {'source': {'id': None, 'name': 'Businesspost.co.kr'},
   'author': None,
   'title': "LG엔솔 배터리 '게임 체인저' 건식 코팅 2028년 상용화, 김제영 “건식코팅 LG가 1위” - 비즈니스포스트",
   'description': None,
   'url': 'https://www.businesspost.co.kr/BP?command=article_view&amp;num=357804',
   'urlToImage': None,
   'publishedAt': '2024-07-04T01:55:30Z',
   'content': None},
  {'source': {'id': None, 'name': 'Chosun.com'},
   'author': '조선비즈',
   'title': 'AI붐 타고 수출 효자된 전력기자재, 스마트폰까지 제쳤다 - 조선비즈 - 조선비즈',
   'description': 'AI붐 타고 수출 효자된 전력기자재, 스마트폰까지 제쳤다 산업부, HD현대일렉트릭서 전력기자재 업계 간담회   한전·코트라·무보 K-그리드 수출지원 MOU 체결',
   'url': 'https://biz.chosun.com/policy/policy_sub/2024/07/04/4APX6OBYQFCWZJM6O2WAK232BU/',
   'urlToImage': 'https://biz.chosun.com/resizer/DKYk9ouKmirmCBZ2_NVdrAW4AkI=/1200x630/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosunbiz/MOLRRIWL2RB7FPDQENL362BLXQ.jpg',
   'publishedAt': '2024-07-04T01:44:00Z',
   'content': None},
  {'source': {'id': None, 'name': 'Chosun.com'},
   'author': '조선일보',
   'title': 'AI반도체 시급한 중국, 유학생까지 동원하며 엔비디아 칩 밀수 - 조선일보',
   'description': 'AI반도체 시급한 중국, 유학생까지 동원하며 엔비디아 칩 밀수',
   'url': 'https://www.chosun.com/economy/tech_it/2024/07/04/GKOMTMFN6VC3DEFGJED5ASM4BE/',
   'urlToImage': 'https://images.chosun.com/resizer/jD1rjZfu7LHLAZzC2CAkGZ7Jtwc=/1200x630/smart/cloudfront-ap-northeast-1.images.arcpublishing.com/chosun/FJSVCXQLHIKETLRJRPOQ6PXFME.jpg',
   'publishedAt': '2024-07-04T01:33:00Z',
   'content': None},
  {'source': {'id': None, 'name': 'Newdaily.co.kr'},
   'author': None,
   'title': "[단독] '가계대출 비상등' 국민은행, 씨티은행 대환대출 이자지원 중단 - 뉴데일리경제",
   'description': 'KB국민은행이 한국씨티은행과의 제휴를 통해 대환대출 고객들에게 제공해 온 이자지원을 중단한 것으로 확인됐다.금융당국이 다시금 가계대출 증가세에 대한 감시의 불을 켜고 있어 부동산담보대출 금리 인상에 이어 대환대출까지 혜택을 대폭 줄이며 속도조절에 나선 것이다.4일 금융권에 따르면 국민은행은 씨티은행 고객들을 대상으로 하는 ‘KB 제휴 대환 신용대출’ 이자지원 혜택을 이달부터 중단했다.앞서 국민은행은 소매금융 사업에서 철수한...',
   'url': 'https://biz.newdaily.co.kr/site/data/html/2024/07/04/2024070400074.html',
   'urlToImage': 'https://image.newdaily.co.kr/site/data/img/2024/07/04/2024070400074_0.jpg',
   'publishedAt': '2024-07-04T01:30:17Z',
   'content': None}]}

In [34]:
json_data = pd.json_normalize(json.loads(response.text)['articles'])
json_data

,author,title,description,url,urlToImage,publishedAt,content,source.id,source.name
0,김지숙,"삼성전자, 조직 개편 'HBM 개발팀' 신설…“HBM에 더 집중” - KBS뉴스",삼성전자가 HBM(고대역폭 메모리) 개발팀을 신설했습니다.<br /> <br />삼...,https://news.kbs.co.kr/news/view.do?ncd=8003727,http://news.kbs.co.kr/data/news/2024/07/04/202...,2024-07-04T06:20:00Z,"HBM( ) .(DS) (4) HBM .\r\nHBM , D .\r\nHBM HBM...",None,Kbs.co.kr
1,정윤교 기자,"골드만삭스 ""한은 8월 금리 인하할 것…하반기 물가 2.0%로 둔화"" - 연합인포맥스",유력 투자은행 골드만삭스는 한국은행이 올해 8월 기준금리 인하에 나설 것으로 전망했...,https://news.einfomax.co.kr/news/articleView.h...,https://cdn.news.einfomax.co.kr/news/thumbnail...,2024-07-04T05:57:35Z,[ . DB ]\r\n(=) = 8 . 2.0% .\r\n3() 11 ( ) .\r...,None,Einfomax.co.kr
2,안태호,10명한테 물어놓고 “10명 중 9명 합격”…에듀윌 과태료 500만원 - 한겨레,공무원 온라인 강의 서비스를 제공하는 에듀윌이 단 10명만 응답한 설문 결과를 근거...,https://www.hani.co.kr/arti/economy/economy_ge...,https://flexible.img.hani.co.kr/flexible/norma...,2024-07-04T05:22:00Z,None,None,Hani.co.kr
3,김기훈,서울 기후동행카드에 남양주시 참여…8월 별내·진접선 적용 - 연합뉴스,(서울=연합뉴스) 김기훈 기자 = 8월 지하철 8호선의 연장 별내선 개통에 맞춰 별...,https://www.yna.co.kr/view/AKR20240704018700004,https://img4.yna.co.kr/photo/yna/YH/2024/07/04...,2024-07-04T05:10:00Z,- (=) 4 - . 2024.7.4 [ . DB ] photo@yna.co.kr\...,None,Yna.co.kr
4,이덕주,“빅테크 꼭지 신호인가?”...젠슨 황 이어 베이조스도 주식 매각 나선다 - 매일경제,최근 신고가를 경신하고 있는 주요 빅테크 기업들의 창업자들이 주식을 매각하면서 주가...,https://www.mk.co.kr/news/business/11058688,https://wimg-orig.mk.co.kr/news/cms/202407/04/...,2024-07-04T04:53:51Z,.\r\n3() CEO 130 (SEC) . 130 16900( 2300) .\r\...,None,Mk.co.kr
5,떤 풍(Tan phung) 기자,"베트남 총리, 삼성전자 평택캠퍼스 방문…방한일정 마무리 - 인사이드비나","[인사이드비나=하노이, 떤 풍(Tan phung) 기자] 팜 민 찐(Pham Min...",http://www.insidevina.com/news/articleView.htm...,http://www.insidevina.com/news/thumbnail/20240...,2024-07-04T04:24:07Z,"[=, (Tan phung) ] (Pham Minh Chinh) 3 , .\r\n...",None,Insidevina.com
6,윤수현 기자,"넷플릭스, 베이직 요금제 완전 폐지 수순 - 미디어오늘",넷플릭스가 캐나다·영국에서 베이직 요금제를 완전 폐지하기로 했다. 베이직 요금제 유...,https://www.mediatoday.co.kr/news/articleView....,https://cdn.mediatoday.co.kr/news/thumbnail/20...,2024-07-04T04:11:30Z,· . .\r\n IT 2 ( 9500) · “713 . ” . ( 5500) ( ...,None,Mediatoday.co.kr
7,None,"반도체장비 세계 1위 ASML, 화성에 1조원대 연구개발 시설 건립 - 한국무역협회","한국무역협회 무역 통상정보, 회원/업무지원, 무역통계, 협회안내 등 서비스 안내.",https://www.kita.net/board/totalTradeNews/tota...,https://kita.net/imgs/common/kita_logo_mid.png,2024-07-04T04:06:37Z,"1 ASML, 1 \r\n 'ASML- ' \r\n ASML ( ) () \r\n ...",None,Kita.net
8,차은지,편하게 살 빼려다 '실명' 될라…충격 연구결과 나왔다 - 한국경제,"편하게 살 빼려다 '실명' 될라…충격 연구결과 나왔다, ""위고비 복용시 '눈 뇌졸중...",https://www.hankyung.com/article/2024070419307,https://img.hankyung.com/photo/202407/99.34985...,2024-07-04T03:53:55Z,. /=\r\n.3() CNN · ' ' ''(NAION) .\r\nNAION ' ...,None,Hankyung.com
9,경향신문,가상자산사업자 불시 영업종료? 앞으론 한달전에 이용자 보호안 제출해야 - 경향신문,None,https://m.khan.co.kr/economy/finance/article/2...,None,2024-07-04T03:20:00Z,None,None,Khan.co.kr
10,김정현 기자,1분기 가계 여유자금 48조↑…정부 순조달 역대급 - 연합인포맥스,지난 1분기 가계의 여유 자금이 크게 늘어났다. 부동산 분양 물량이 많지 않아 가계...,https://news.einfomax.co.kr/news/articleView.h...,https://cdn.news.einfomax.co.kr/news/thumbnail...,2024-07-04T03:03:26Z,"1 \r\n, \r\n 1 \r\n(=) = 1 . .\r\n . .\r\n 4 2...",None,Einfomax.co.kr
11,None,횡령 여파에 성과급 환수.. 직원들 날벼락 (2024.07.03/뉴스데스크/MBC경...,None,https://www.youtube.com/watch?v=oWjQ407PihA,None,2024-07-04T03:00:36Z,Your browser isnt supported anymore. Update it...,None,YouTube
12,머니투데이,"국민 88%는 금융투자자...""금투세 도입 시 투자 축소"" - 머니투데이",None,https://news.google.com/rss/articles/CBMiN2h0d...,None,2024-07-04T03:00:04Z,None,google-news,Google News
13,문화일보,中 저가 공세에… 철강수출 2년째↓ - 문화일보,None,https://www.munhwa.com/news/view.html?no=20240...,None,2024-07-04T02:59:00Z,None,None,Munhwa.com
14,None,[자막뉴스] 방콕 가는 대한항공 승무원 가방에 소총탄이.. '발칵' (2024.07...,None,https://www.youtube.com/watch?v=-7Xnl_2gtJQ,None,2024-07-04T02:49:03Z,Your browser isnt supported anymore. Update it...,None,YouTube
15,김부미 기자,상반기 모빌리티용 수소 3790t 소비…전년比 46% 증가 - 전기신문,올 상반기 모빌리티용 수소 소비량이 지난해보다 46% 증가한 것으로 나타났다.4일 ...,https://www.electimes.com/news/articleView.htm...,https://cdn.electimes.com/news/thumbnail/20240...,2024-07-04T02:24:16Z,46% .\r\n4 3790t 46% .\r\n 8400t . 13000t .\r\...,None,Electimes.com
16,None,"LG엔솔 배터리 '게임 체인저' 건식 코팅 2028년 상용화, 김제영 “건식코팅 L...",None,https://www.businesspost.co.kr/BP?command=arti...,None,2024-07-04T01:55:30Z,None,None,Businesspost.co.kr
17,조선비즈,"AI붐 타고 수출 효자된 전력기자재, 스마트폰까지 제쳤다 - 조선비즈 - 조선비즈","AI붐 타고 수출 효자된 전력기자재, 스마트폰까지 제쳤다 산업부, HD현대일렉트릭서...",https://biz.chosun.com/policy/policy_sub/2024/...,https://biz.chosun.com/resizer/DKYk9ouKmirmCBZ...,2024-07-04T01:44:00Z,None,None,Chosun.com
18,조선일보,"AI반도체 시급한 중국, 유학생까지 동원하며 엔비디아 칩 밀수 - 조선일보","AI반도체 시급한 중국, 유학생까지 동원하며 엔비디아 칩 밀수",https://www.chosun.com/economy/tech_it/2024/07...,https://images.chosun.com/resizer/jD1rjZfu7LHL...,2024-07-04T01:33:00Z,None,None,Chosun.com
19,None,"[단독] '가계대출 비상등' 국민은행, 씨티은행 대환대출 이자지원 중단 - 뉴데일리경제",KB국민은행이 한국씨티은행과의 제휴를 통해 대환대출 고객들에게 제공해 온 이자지원을...,https://biz.newdaily.co.kr/site/data/html/2024...,https://image.newdaily.co.kr/site/data/img/202...,2024-07-04T01:30:17Z,None,None,Newdaily.co.kr

In [35]:
json_data = json_data.drop(columns=['source.id','content'])

In [36]:
json_data

,author,title,description,url,urlToImage,publishedAt,source.name
0,김지숙,"삼성전자, 조직 개편 'HBM 개발팀' 신설…“HBM에 더 집중” - KBS뉴스",삼성전자가 HBM(고대역폭 메모리) 개발팀을 신설했습니다.<br /> <br />삼...,https://news.kbs.co.kr/news/view.do?ncd=8003727,http://news.kbs.co.kr/data/news/2024/07/04/202...,2024-07-04T06:20:00Z,Kbs.co.kr
1,정윤교 기자,"골드만삭스 ""한은 8월 금리 인하할 것…하반기 물가 2.0%로 둔화"" - 연합인포맥스",유력 투자은행 골드만삭스는 한국은행이 올해 8월 기준금리 인하에 나설 것으로 전망했...,https://news.einfomax.co.kr/news/articleView.h...,https://cdn.news.einfomax.co.kr/news/thumbnail...,2024-07-04T05:57:35Z,Einfomax.co.kr
2,안태호,10명한테 물어놓고 “10명 중 9명 합격”…에듀윌 과태료 500만원 - 한겨레,공무원 온라인 강의 서비스를 제공하는 에듀윌이 단 10명만 응답한 설문 결과를 근거...,https://www.hani.co.kr/arti/economy/economy_ge...,https://flexible.img.hani.co.kr/flexible/norma...,2024-07-04T05:22:00Z,Hani.co.kr
3,김기훈,서울 기후동행카드에 남양주시 참여…8월 별내·진접선 적용 - 연합뉴스,(서울=연합뉴스) 김기훈 기자 = 8월 지하철 8호선의 연장 별내선 개통에 맞춰 별...,https://www.yna.co.kr/view/AKR20240704018700004,https://img4.yna.co.kr/photo/yna/YH/2024/07/04...,2024-07-04T05:10:00Z,Yna.co.kr
4,이덕주,“빅테크 꼭지 신호인가?”...젠슨 황 이어 베이조스도 주식 매각 나선다 - 매일경제,최근 신고가를 경신하고 있는 주요 빅테크 기업들의 창업자들이 주식을 매각하면서 주가...,https://www.mk.co.kr/news/business/11058688,https://wimg-orig.mk.co.kr/news/cms/202407/04/...,2024-07-04T04:53:51Z,Mk.co.kr
5,떤 풍(Tan phung) 기자,"베트남 총리, 삼성전자 평택캠퍼스 방문…방한일정 마무리 - 인사이드비나","[인사이드비나=하노이, 떤 풍(Tan phung) 기자] 팜 민 찐(Pham Min...",http://www.insidevina.com/news/articleView.htm...,http://www.insidevina.com/news/thumbnail/20240...,2024-07-04T04:24:07Z,Insidevina.com
6,윤수현 기자,"넷플릭스, 베이직 요금제 완전 폐지 수순 - 미디어오늘",넷플릭스가 캐나다·영국에서 베이직 요금제를 완전 폐지하기로 했다. 베이직 요금제 유...,https://www.mediatoday.co.kr/news/articleView....,https://cdn.mediatoday.co.kr/news/thumbnail/20...,2024-07-04T04:11:30Z,Mediatoday.co.kr
7,None,"반도체장비 세계 1위 ASML, 화성에 1조원대 연구개발 시설 건립 - 한국무역협회","한국무역협회 무역 통상정보, 회원/업무지원, 무역통계, 협회안내 등 서비스 안내.",https://www.kita.net/board/totalTradeNews/tota...,https://kita.net/imgs/common/kita_logo_mid.png,2024-07-04T04:06:37Z,Kita.net
8,차은지,편하게 살 빼려다 '실명' 될라…충격 연구결과 나왔다 - 한국경제,"편하게 살 빼려다 '실명' 될라…충격 연구결과 나왔다, ""위고비 복용시 '눈 뇌졸중...",https://www.hankyung.com/article/2024070419307,https://img.hankyung.com/photo/202407/99.34985...,2024-07-04T03:53:55Z,Hankyung.com
9,경향신문,가상자산사업자 불시 영업종료? 앞으론 한달전에 이용자 보호안 제출해야 - 경향신문,None,https://m.khan.co.kr/economy/finance/article/2...,None,2024-07-04T03:20:00Z,Khan.co.kr
10,김정현 기자,1분기 가계 여유자금 48조↑…정부 순조달 역대급 - 연합인포맥스,지난 1분기 가계의 여유 자금이 크게 늘어났다. 부동산 분양 물량이 많지 않아 가계...,https://news.einfomax.co.kr/news/articleView.h...,https://cdn.news.einfomax.co.kr/news/thumbnail...,2024-07-04T03:03:26Z,Einfomax.co.kr
11,None,횡령 여파에 성과급 환수.. 직원들 날벼락 (2024.07.03/뉴스데스크/MBC경...,None,https://www.youtube.com/watch?v=oWjQ407PihA,None,2024-07-04T03:00:36Z,YouTube
12,머니투데이,"국민 88%는 금융투자자...""금투세 도입 시 투자 축소"" - 머니투데이",None,https://news.google.com/rss/articles/CBMiN2h0d...,None,2024-07-04T03:00:04Z,Google News
13,문화일보,中 저가 공세에… 철강수출 2년째↓ - 문화일보,None,https://www.munhwa.com/news/view.html?no=20240...,None,2024-07-04T02:59:00Z,Munhwa.com
14,None,[자막뉴스] 방콕 가는 대한항공 승무원 가방에 소총탄이.. '발칵' (2024.07...,None,https://www.youtube.com/watch?v=-7Xnl_2gtJQ,None,2024-07-04T02:49:03Z,YouTube
15,김부미 기자,상반기 모빌리티용 수소 3790t 소비…전년比 46% 증가 - 전기신문,올 상반기 모빌리티용 수소 소비량이 지난해보다 46% 증가한 것으로 나타났다.4일 ...,https://www.electimes.com/news/articleView.htm...,https://cdn.electimes.com/news/thumbnail/20240...,2024-07-04T02:24:16Z,Electimes.com
16,None,"LG엔솔 배터리 '게임 체인저' 건식 코팅 2028년 상용화, 김제영 “건식코팅 L...",None,https://www.businesspost.co.kr/BP?command=arti...,None,2024-07-04T01:55:30Z,Businesspost.co.kr
17,조선비즈,"AI붐 타고 수출 효자된 전력기자재, 스마트폰까지 제쳤다 - 조선비즈 - 조선비즈","AI붐 타고 수출 효자된 전력기자재, 스마트폰까지 제쳤다 산업부, HD현대일렉트릭서...",https://biz.chosun.com/policy/policy_sub/2024/...,https://biz.chosun.com/resizer/DKYk9ouKmirmCBZ...,2024-07-04T01:44:00Z,Chosun.com
18,조선일보,"AI반도체 시급한 중국, 유학생까지 동원하며 엔비디아 칩 밀수 - 조선일보","AI반도체 시급한 중국, 유학생까지 동원하며 엔비디아 칩 밀수",https://www.chosun.com/economy/tech_it/2024/07...,https://images.chosun.com/resizer/jD1rjZfu7LHL...,2024-07-04T01:33:00Z,Chosun.com
19,None,"[단독] '가계대출 비상등' 국민은행, 씨티은행 대환대출 이자지원 중단 - 뉴데일리경제",KB국민은행이 한국씨티은행과의 제휴를 통해 대환대출 고객들에게 제공해 온 이자지원을...,https://biz.newdaily.co.kr/site/data/html/2024...,https://image.newdaily.co.kr/site/data/img/202...,2024-07-04T01:30:17Z,Newdaily.co.kr

In [44]:
# 페이지 수 계산
num_pages = (total_articles + page_size - 1) // page_size

# 모든 기사를 저장할 리스트
all_articles = []

# 각 페이지에 대한 API 호출
for page in range(num_pages):
    # 페이지 번호를 포함한 URL 생성
    page_url = f'{url}&page={page + 1}'

    # API 호출
    response = requests.get(page_url)

    # 응답이 성공적인지 확인
    if response.status_code == 200:
        # 응답에서 기사 데이터 추출
        articles = json.loads(response.text)['articles']

        # content 열과 source.id 필드를 제거한 기사 리스트 생성
        for article in articles:
            if 'content' in article:
                del article['content']
            if 'source' in article and 'id' in article['source']:
                del article['source']['id']


        # 전체 기사 리스트에 추가
        all_articles.extend(articles)
    else:
        # 에러 처리
        print(f"Error fetching articles: {response.status_code}")
        break

# 파일을 저장할 경로 정의
file_path = '/content/drive/My Drive/all_articles.json'

# 전체 기사 리스트를 JSON 파일로 저장
with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(all_articles, f, indent=4, ensure_ascii=False)

# 확인 메시지 출력
print(f"All articles saved to: {file_path}")

All articles saved to: /content/drive/My Drive/all_articles.json

In [57]:
import json
from google.colab import drive

# 구글 드라이브 마운트
drive.mount('/content/drive')

# 파일 경로 정의
file_path = '/content/drive/My Drive/all_articles.json'

# JSON 파일의 내용 확인
with open(file_path, 'r', encoding='utf-8') as f:
    data = f.read()
    print(data[:1000])  # 처음 1000자만 출력하여 확인

    json_data = json.loads(data)
    df = pd.json_normalize(json_data)

# DataFrame 출력 (필요에 따라 출력 방법 변경 가능)
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[
    {
        "source": {
            "name": "Kbs.co.kr"
        },
        "author": "김지숙",
        "title": "삼성전자, 조직 개편 'HBM 개발팀' 신설…“HBM에 더 집중” - KBS뉴스",
        "description": "삼성전자가 HBM(고대역폭 메모리) 개발팀을 신설했습니다.<br /> <br />삼성전자 디바이스솔루션(DS) 부문은 오늘(4일) HBM 개발팀 신설을 골자로 하는 조직 개편을 실시했습니다.<br /> <br />메모리사업부 내에 있었던 HBM 전담 조직을 팀으로 신설한 것으로, 신임 팀장은 고성능 D램 제품 설계 전문가인 손영수 부사장이 맡기로 했습니다.<br /> <br />이 같은 HBM 개발팀 신설은 인공지능 시장 확대로 HBM 수요가 급증하면서, HB…",
        "url": "https://news.kbs.co.kr/news/view.do?ncd=8003727",
        "urlToImage": "http://news.kbs.co.kr/data/news/2024/07/04/20240704_qmlaaV.jpg",
        "publishedAt": "2024-07-04T06:20:00Z"
    },
    {
        "source": {
            "name": "Einfomax.co.kr"
        },
        "author": "정윤교 기자",
        "title": "골드만삭스 \"한은 8월 금리 인하할 것…하반기 물가 2.0%로 둔화\" - 연합인포맥스",
        "description": "유력 투자은행 골드만삭스는 한국은행이 올해 8월 기준금리 인하에 나설 것으로 전망했다. 올해 하반기 국내 소비자물가 상승률이 한국은행의 목표치인 2.0%로 둔화할 것으로 내다보면서다.3일(현지시간) 다우존스에 따르면 골드만삭스 애널리스트들은 오는 11일 한국은행 금융

,author,title,description,url,urlToImage,publishedAt,source.name
0,김지숙,"삼성전자, 조직 개편 'HBM 개발팀' 신설…“HBM에 더 집중” - KBS뉴스",삼성전자가 HBM(고대역폭 메모리) 개발팀을 신설했습니다.<br /> <br />삼...,https://news.kbs.co.kr/news/view.do?ncd=8003727,http://news.kbs.co.kr/data/news/2024/07/04/202...,2024-07-04T06:20:00Z,Kbs.co.kr
1,정윤교 기자,"골드만삭스 ""한은 8월 금리 인하할 것…하반기 물가 2.0%로 둔화"" - 연합인포맥스",유력 투자은행 골드만삭스는 한국은행이 올해 8월 기준금리 인하에 나설 것으로 전망했...,https://news.einfomax.co.kr/news/articleView.h...,https://cdn.news.einfomax.co.kr/news/thumbnail...,2024-07-04T05:57:35Z,Einfomax.co.kr
2,안태호,10명한테 물어놓고 “10명 중 9명 합격”…에듀윌 과태료 500만원 - 한겨레,공무원 온라인 강의 서비스를 제공하는 에듀윌이 단 10명만 응답한 설문 결과를 근거...,https://www.hani.co.kr/arti/economy/economy_ge...,https://flexible.img.hani.co.kr/flexible/norma...,2024-07-04T05:22:00Z,Hani.co.kr
3,김기훈,서울 기후동행카드에 남양주시 참여…8월 별내·진접선 적용 - 연합뉴스,(서울=연합뉴스) 김기훈 기자 = 8월 지하철 8호선의 연장 별내선 개통에 맞춰 별...,https://www.yna.co.kr/view/AKR20240704018700004,https://img4.yna.co.kr/photo/yna/YH/2024/07/04...,2024-07-04T05:10:00Z,Yna.co.kr
4,이덕주,“빅테크 꼭지 신호인가?”...젠슨 황 이어 베이조스도 주식 매각 나선다 - 매일경제,최근 신고가를 경신하고 있는 주요 빅테크 기업들의 창업자들이 주식을 매각하면서 주가...,https://www.mk.co.kr/news/business/11058688,https://wimg-orig.mk.co.kr/news/cms/202407/04/...,2024-07-04T04:53:51Z,Mk.co.kr
...,...,...,...,...,...,...,...
65,박윤수,'해외 원정 성형' 의사‥역외탈세 무더기 적발 - MBC 뉴스,갈수록 치밀해지는 역외 탈세 수법에 금융당국이 적발에 나섰습니다. 동남아 원정 진료...,https://imnews.imbc.com/replay/2024/nwtoday/ar...,https://image.imnews.imbc.com/replay/2024/nwto...,2024-07-02T21:52:08Z,Imbc.com
66,박해윤 기자,청사진 공개된 롯바 송도 바이오캠퍼스…미국 시러큐스 캠퍼스 연계로 글로벌 시장 공략...,롯데바이오로직스가 인천 송도국제도시에 들어서는 36만ℓ 규모 바이오 캠퍼스와 미국 ...,https://www.incheonilbo.com/news/articleView.h...,https://www.incheonilbo.com/news/thumbnail/202...,2024-07-02T21:00:00Z,Incheonilbo.com
67,강동헌,"""금리 인하땐 제조업 AI투자 활발해져…반도체, 전력설비 등 주목"" - 서울경제신문",증권 > 증권일반 뉴스: 투자 전문가들은 서울경제신문이 2일 주최한 ‘머니트렌드 2...,https://www.sedaily.com/NewsView/2DBLI4LCJ3,https://newsimg.sedaily.com/2024/07/03/2DBLI4L...,2024-07-02T21:00:00Z,Sedaily.com
68,한지훈 기자,글로벌 진격... '퍼스트 디센던트' 3시간 만에 동접 17만 돌파 - 게임플,‘퍼스트 디센던트’에 대한 글로벌 게이머들의 관심이 엄청나다. 출시 당일 단 3시간...,https://www.gameple.co.kr/news/articleView.htm...,https://cdn.gameple.co.kr/news/photo/202407/21...,2024-07-02T11:11:34Z,Gameple.co.kr
69,박주희,대구서 월급 꼬박 모아 아파트 사는 데 걸리는 시간은? - 영남일보,올해 대구에서 월급을 꼬박 모아 아파트를 구입하는 데 9.5년이 걸리는 것으로 조사...,https://www.yeongnam.com/web/view.php?key=2024...,https://www.yeongnam.com/mnt/file/202407/20240...,2024-07-02T10:45:14Z,Yeongnam.com

No charts were generated by quickchart

In [45]:
# JSON 응답을 로드합니다.

data = response.json()

# 데이터프레임으로 변환합니다.
df = pd.json_normalize(data['articles'])

# 데이터프레임을 출력합니다.
print(df)

   author                                              title  \
0     민수정     "이게 5000원짜리 백반" 반찬만 13개…노부부 식당에 뜨거운 반응 - 머니투데이
1     이정현             테슬라, 차량 인도량 전망치 상회…주가 10% 급등 - ZD넷 코리아
2    None     HLB, FDA와 공장실사 보완 위한 미팅 완료…“추가 보완사항 없다” - 더바이오
3     이소은    "송파구보다 비싸"…서울 아닌데 '평균 아파트값 16.3억' 찍은 이곳 - 머니투데이
4     홍장원  일론 머스크 “테슬라 공매도 파멸할 것, 그게 빌 게이츠라도 마찬가지” [월가월부]...
5     박윤수                 '해외 원정 성형' 의사‥역외탈세 무더기 적발 - MBC 뉴스
6  박해윤 기자  청사진 공개된 롯바 송도 바이오캠퍼스…미국 시러큐스 캠퍼스 연계로 글로벌 시장 공략...
7     강동헌     "금리 인하땐 제조업 AI투자 활발해져…반도체, 전력설비 등 주목" - 서울경제신문
8  한지훈 기자        글로벌 진격... '퍼스트 디센던트' 3시간 만에 동접 17만 돌파 - 게임플
9     박주희              대구서 월급 꼬박 모아 아파트 사는 데 걸리는 시간은? - 영남일보

                                         description  \
0  푸짐한 한 끼를 제공하는 부산의 한 백반집이 화제다. 밥과 국을 제외하고 반찬 13...
1  테슬라의 2분기 자동차 생산량과 인도량이 예상을 크게 넘어선 것으로 나타났다. 이 ...
2                                               None
3  '준강남'으로 불리는 경기도 과천시 평균 아파트 매맷값이 서울 비강남권은 물론, 분...
4  2일(현지시간) 미국 S&P500 지수가 사상 처음으로 5500선 위에서 장을 마쳤...
5  갈수록 치밀해지는 역외 탈세 수법에 금융당국이 적발에 나섰습니다. 동남아 원정 진료...
6  롯데바이오로직스가 인천 송도국제도시에 들어서는 36만ℓ 규모 바이오 캠퍼스와 미국 ...
7  증권 > 증권일반 뉴스: 투자 전문가들은 서울경제신문이 2일 주최한 ‘머니트렌드 2...
8  ‘퍼스트 디센던트’에 대한 글로벌 게이머들의 관심이 엄청나다. 출시 당일 단 3시간...
9  올해 대구에서 월급을 꼬박 모아 아파트를 구입하는 데 9.5년이 걸리는 것으로 조사...

                                                 url  \
0  https://news.mt.co.kr/mtview.php?no=2024070309...
1        https://zdnet.co.kr/view/?no=20240703075744
2         https://admin.google.com/ServiceNotAllowed
3  https://news.mt.co.kr/mtview.php?no=2024070307...
4           https://www.mk.co.kr/news/stock/11057256
5  https://imnews.imbc.com/replay/2024/nwtoday/ar...
6  https://www.incheonilbo.com/news/articleView.h...
7        https://www.sedaily.com/NewsView/2DBLI4LCJ3
8  https://www.gameple.co.kr/news/articleView.htm...
9  https://www.yeongnam.com/web/view.php?key=2024...

                                          urlToImage           publishedAt  \
0  https://thumb.mt.co.kr/21/2024/07/202407030901...  2024-07-03T00:57:58Z
1  https://image.zdnet.co.kr/2021/03/12/8d6b4dd0e...  2024-07-02T23:33:49Z
2                                               None  2024-07-02T23:31:12Z
3  https://thumb.mt.co.kr/21/2024/07/202407030746...  2024-07-02T23:24:22Z
4  https://wimg-orig.mk.co.kr/news/cms/202407/03/...  2024-07-02T22:10:02Z
5  https://image.imnews.imbc.com/replay/2024/nwto...  2024-07-02T21:52:08Z
6  https://www.incheonilbo.com/news/thumbnail/202...  2024-07-02T21:00:00Z
7  https://newsimg.sedaily.com/2024/07/03/2DBLI4L...  2024-07-02T21:00:00Z
8  https://cdn.gameple.co.kr/news/photo/202407/21...  2024-07-02T11:11:34Z
9  https://www.yeongnam.com/mnt/file/202407/20240...  2024-07-02T10:45:14Z

                                             content    source.id  \
0  . 13 ' 5000' . 3 A . A 5000 . \r\n. 13 , . A "...         None
1  2 . 2() 10%  CNBC .\r\n 2 443956 . 439 . 1 14....         None
2  We are sorry, but you do not have access to Go...  google-news
3  '' , . 3 1 · 163603 ·· .\r\n245650 242370, 234...         None
4  2() S&amp;P500 5500 .\r\n S&amp;P500 33.92(0.6...         None
5  .\r\n, .\r\n.\r\nA .\r\n.\r\n.\r\n, .\r\n.\r\n...         None
6  36 .\r\n 2 .\r\n 10 . 202285.2 , 3 1 2, 3 36 ....         None
7  viewer\r\n 2 2024 3 . \r\n2 2024 (AI) . . AI ,...         None
8  ‘ ’ . 3 17 .\r\n ‘ ’ 2 .\r\n 9 5 .\r\n . 3 17 ...         None
9  9.5 . (2020~2021) 2018(9.3) .\r\n2 PIR( , 84 )...         None

       source.name
0         Mt.co.kr
1      Zdnet.co.kr
2      Google News
3         Mt.co.kr
4         Mk.co.kr
5         Imbc.com
6  Incheonilbo.com
7      Sedaily.com
8    Gameple.co.kr
9     Yeongnam.com